
server:
#  port: 64000
  port: ${PORT:0}
spring:
  application:
    name: catalog
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/infnet-pb-at
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        globally_quoted_identifiers: true
  sql:
    init:
      mode: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


