server:
  port: ${PORT:0}
spring:
  application:
    name: catalog
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/infnet-pb-at
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        globally_quoted_identifiers: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true

