server:
#  port: ${PORT:0}
  port: 64002
spring:
  application:
    name: delivery
  data:
    mongodb:
      auto-index-creation: true
      host: localhost
#      host: db
      port: 27017
      database: infnet-pb-at
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://host.docker.internal:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


